# Generated by Django 6.0.1 on 2026-01-24 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('boarding', 'Boarding'), ('departed', 'Departed')], default='scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('aadvantage_number', models.CharField(blank=True, max_length=20, null=True)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2)),
                ('seat_preference', models.CharField(blank=True, choices=[('window', 'Window'), ('aisle', 'Aisle'), ('middle', 'Middle')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('changed', 'Changed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.CharField(blank=True, max_length=5, null=True)),
                ('segment_order', models.PositiveSmallIntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_segments', to='api.reservation')),
            ],
            options={
                'ordering': ['segment_order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('greeting', 'Greeting'), ('lookup', 'Lookup'), ('viewing', 'Viewing'), ('changing', 'Changing'), ('confirming', 'Confirming'), ('complete', 'Complete')], default='greeting', max_length=20)),
                ('helper_link', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('family', 'Family')], max_length=10)),
                ('content', models.TextField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('entities', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
