# Generated by Django 6.0.1 on 2026-01-25 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='helper_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='helper_link_mode',
            field=models.CharField(choices=[('session', 'Session-based (30 min)'), ('persistent', 'Persistent (until flight departure)')], default='session', max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('action_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('failed', 'Failed')], default='executed', max_length=20)),
                ('family_notes', models.TextField(blank=True)),
                ('result_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_actions', to='api.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
