# Generated by Django 4.2.27 on 2026-01-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_location_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passengerlocation',
            new_name='api_passeng_session_73ad30_idx',
            old_name='api_passeng_session_a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='action_type',
            field=models.CharField(choices=[('change_flight', 'Change Flight'), ('cancel_flight', 'Cancel Flight'), ('select_seat', 'Select Seat'), ('add_bags', 'Add Bags'), ('request_wheelchair', 'Request Wheelchair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='status',
            field=models.CharField(choices=[('executed', 'Executed'), ('failed', 'Failed')], default='executed', max_length=10),
        ),
        migrations.AlterField(
            model_name='locationalert',
            name='alert_type',
            field=models.CharField(choices=[('running_late', 'Running Late'), ('urgent', 'Urgent - May Miss Flight'), ('arrived', 'Arrived at Gate')], max_length=20),
        ),
    ]
