# Generated by Django 6.0.1 on 2026-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_api_passeng_session_a1b2c3_idx_api_passeng_session_73ad30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='helper_link_mode',
            field=models.CharField(choices=[('session', 'Session-based (30 min)'), ('persistent', 'Persistent (until flight departure)'), ('demo', 'Demo mode (2 hours)')], default='session', max_length=20),
        ),
    ]
