"""URL configuration for AA Voice Concierge API."""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router for CRUD ViewSets
router = DefaultRouter()
router.register(r'passengers', views.PassengerViewSet, basename='passenger')
router.register(r'flights-db', views.FlightViewSet, basename='flight-db')
router.register(r'reservations', views.ReservationViewSet, basename='reservation')
router.register(r'flight-segments', views.FlightSegmentViewSet, basename='flight-segment')
router.register(r'sessions', views.SessionViewSet, basename='session')
router.register(r'messages', views.MessageViewSet, basename='message')

urlpatterns = [
    # CRUD endpoints (auto-generated by router)
    path('', include(router.urls)),

    # Conversation endpoints
    path('conversation/start', views.start_conversation, name='start_conversation'),
    path('conversation/message', views.send_message, name='send_message'),
    path('conversation/<uuid:session_id>', views.get_session, name='get_session'),

    # Reservation endpoints (legacy)
    path('reservation/lookup', views.lookup_reservation, name='lookup_reservation'),
    path('reservation/change', views.change_reservation, name='change_reservation'),

    # Flight endpoints (using AA Flight-Engine API)
    path('flights/', views.get_flights, name='get_flights'),
    path('flights/search', views.search_flights, name='search_flights'),
    path('flights/alternatives', views.get_alternative_flights_view, name='get_alternative_flights'),

    # Airport endpoints (using AA Flight-Engine API)
    path('airports/', views.get_airports, name='get_airports'),

    # Voice endpoints
    path('voice/synthesize', views.synthesize_voice, name='synthesize_voice'),

    # Family helper endpoints
    path('helper/create-link', views.create_helper_link, name='create_helper_link'),
    path('helper/<str:link_id>', views.get_helper_session, name='get_helper_session'),
    path('helper/<str:link_id>/suggest', views.send_helper_suggestion, name='send_helper_suggestion'),
    
    # Health check
    path('health/', views.health_check, name='health_check'),
]
