"""URL configuration for AA Voice Concierge API."""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router for CRUD ViewSets
router = DefaultRouter()
router.register(r'passengers', views.PassengerViewSet, basename='passenger')
router.register(r'flights-db', views.FlightViewSet, basename='flight-db')
router.register(r'reservations', views.ReservationViewSet, basename='reservation')
router.register(r'flight-segments', views.FlightSegmentViewSet, basename='flight-segment')
router.register(r'sessions', views.SessionViewSet, basename='session')
router.register(r'messages', views.MessageViewSet, basename='message')

urlpatterns = [
    # CRUD endpoints (auto-generated by router)
    path('', include(router.urls)),

    # Conversation endpoints
    path('conversation/start', views.start_conversation, name='start_conversation'),
    path('conversation/message', views.send_message, name='send_message'),
    path('conversation/<uuid:session_id>', views.get_session, name='get_session'),

    # Reservation endpoints
    path('reservation/lookup', views.lookup_reservation, name='lookup_reservation'),
    path('reservation/change', views.change_reservation, name='change_reservation'),
    path('reservation/create', views.create_reservation, name='create_reservation'),

    # Flight endpoints (using AA Flight-Engine API)
    path('flights/', views.get_flights, name='get_flights'),
    path('flights/search', views.search_flights, name='search_flights'),
    path('flights/alternatives', views.get_alternative_flights_view, name='get_alternative_flights'),

    # Airport endpoints (using AA Flight-Engine API)
    path('airports/', views.get_airports, name='get_airports'),

    # Voice endpoints
    path('voice/synthesize', views.synthesize_voice, name='synthesize_voice'),

    # Family helper endpoints
    path('helper/create-link', views.create_helper_link, name='create_helper_link'),
    path('helper/<str:link_id>', views.get_helper_session, name='get_helper_session'),
    path('helper/<str:link_id>/suggest', views.send_helper_suggestion, name='send_helper_suggestion'),

    # Family helper action endpoints
    path('helper/<str:link_id>/actions', views.get_helper_actions, name='get_helper_actions'),
    path('helper/<str:link_id>/actions/change-flight', views.helper_change_flight, name='helper_change_flight'),
    path('helper/<str:link_id>/actions/cancel-flight', views.helper_cancel_flight, name='helper_cancel_flight'),
    path('helper/<str:link_id>/actions/select-seat', views.helper_select_seat, name='helper_select_seat'),
    path('helper/<str:link_id>/actions/add-bags', views.helper_add_bags, name='helper_add_bags'),
    path('helper/<str:link_id>/actions/request-wheelchair', views.helper_request_wheelchair, name='helper_request_wheelchair'),
    path('helper/<str:link_id>/flights', views.helper_get_flights, name='helper_get_flights'),
    path('helper/<str:link_id>/seats', views.helper_get_seats, name='helper_get_seats'),
    
    # Health check
    path('health/', views.health_check, name='health_check'),

    # Retell AI Voice Agent endpoints
    path('retell/status', views.retell_status, name='retell_status'),
    path('retell/agents', views.retell_list_agents, name='retell_list_agents'),
    path('retell/agents/create', views.retell_create_agent, name='retell_create_agent'),
    path('retell/agents/<str:agent_id>', views.retell_get_agent, name='retell_get_agent'),
    path('retell/calls/web', views.retell_create_web_call, name='retell_create_web_call'),
    path('retell/calls/phone', views.retell_create_phone_call, name='retell_create_phone_call'),
    path('retell/calls/<str:call_id>', views.retell_get_call, name='retell_get_call'),
    path('retell/calls/<str:call_id>/end', views.retell_end_call, name='retell_end_call'),

    # Retell Webhook endpoints (for Retell to call your backend)
    path('retell/webhook', views.retell_webhook, name='retell_webhook'),
    path('retell/function', views.retell_function_call, name='retell_function_call'),
    path('retell/functions', views.retell_function_definitions, name='retell_function_definitions'),


    # Outbound Reminder endpoints (Retell outbound calls)
    path('reminders/status', views.reminder_status, name='reminder_status'),
    path('reminders/gate-closing', views.send_gate_reminders, name='send_gate_reminders'),
    path('reminders/departure', views.send_departure_reminders, name='send_departure_reminders'),
    path('reminders/manual', views.send_manual_reminder, name='send_manual_reminder'),
    path('reminders/upcoming', views.get_upcoming_flights_for_reminders, name='get_upcoming_flights_for_reminders'),

    # Location tracking endpoints
    path('location/update', views.update_location, name='update_location'),
    path('location/alert', views.trigger_location_alert, name='trigger_location_alert'),
    path('location/<uuid:session_id>/history', views.get_location_history, name='get_location_history'),
    path('location/<uuid:session_id>/alerts', views.get_location_alerts, name='get_location_alerts'),
    path('location/alerts/<uuid:alert_id>/acknowledge', views.acknowledge_alert, name='acknowledge_alert'),
    path('helper/<str:link_id>/location', views.get_helper_location, name='get_helper_location'),
]
